### PR TITLE
enable mathjax equation numbering by default

### PR DESCRIPTION
**Pull request by greole**
It would be great if the nbviewer could handle numbered mathjax equations.

Check http://stackoverflow.com/questions/18823779/ipython-notebook-and-mathjax-labeled-equations
for more details

### CODE REVIEW

**Comment by bollwyvl** [comment]
I agree in principal. Here on nbviewer, We should move mathjax config to it's own block so that slides, etc. can use it.

Upstream, as has been discussed, configuring mathjax at the metadata level would let people add numbering, or disable math altogether...

**Comment by minrk** [comment]
Equation numbering is problematic in the live notebook because the number increments based on render order, rather than order on the page, so you get weird numbers. Nbviewer shouldn't have this problem, so I think it makes sense to enable it. The only peculiarity, then, is that it's a mismatch with the live notebook.

**Comment by bollwyvl** [comment]
Great. I'll jigger the blocks so this happens in other formats. Might be a
nice opportunity to do a mathjax url config as well.

**Comment by rgbkrk** [comment]
Fair points.

**Comment by bollwyvl** [comment]
Jiggering on greole/nbviewer#1.

**Comment by damianavila** [comment]
I am little worried about the fact that people will see numbering in nbviewer and then they will push for numbering working OK in the live notebook...

**Comment by greole** [comment]
That is a valid point. However writing scientific reports without numbering is nearly impossible. I could live with a live notebook where I have to turn on numbering myself, but sharing a notebook with colleagues via nbviewer is a big issue. 

Currently to get numbering on nbviewer I use

    from IPython.display import HTML
    js = r""" <script type="text/Javascript"> MathJax.Hub.Config({ TeX: { equationNumbers: { autoNumber: "AMS", useLabelIds: true } }});
    </script> """
    HTML(js)
 
in a code cell. Couldn't this be simplified to something like

    from IPython.external.mathjax import enable_nbviewer_numbering 

which just spits out the corresponding js. That way it is possible to enable numbering in a simple, non disturbing way and turned off until explicitly demanded.

**Comment by cstarknyc** [comment]
The js hack (Greole's) works nicely for an IPython notebook in Jupyter, but won't and doesn't work when rendered in GitHub. The practical effect is that communication with colleagues is compromised, since only those with Python set up can see the math line numbers.

**Comment by bollwyvl** [comment]
> only those with Python

Or a web browser and, you know, nbviewer.org... Or perhaps i misunderstand
your comment.

**Comment by cstarknyc** [comment]
Private GitHub repo, so as far as I know nbviewer can't do it's thing.

**Comment by bollwyvl** [comment]
Indeed!

This use case is supported by hosting your own nbviewer and having a Github
api key for a robot which has access to those repos. This allows you any
kind of customization that your team may need, without making your host
your own github.

**Pull request merged**
