### PR TITLE
update link to iruby notebook

### PR DESCRIPTION
**Pull request by minad**
the location of the notebook has been changed

### CODE REVIEW

**Comment by bollwyvl** [comment]
Great! Looks like the nyaplot isn't showing up, but I'll merge right now.

http://nbviewer.ipython.org/github/SciRuby/sciruby-notebooks/blob/master/getting_started.ipynb#Nyaplot

Also, in working on the jupyter kernels marketing page:

https://github.com/jupyter/jupyter.github.io/pull/7
Would love your feedback!

**Comment by minad** [comment]
@bollwyvl thx. iruby is now also available on try.jupyter.org. Furthermore I am working on a container https://github.com/SciRuby/sciruby-notebooks/blob/master/Dockerfile but this is not yet finished.

**Comment by minad** [comment]
And  the logo, you can use https://github.com/SciRuby/iruby/tree/master/logo

The new design looks nice! When will you deploy this?

**Comment by minad** [comment]
@bollwyvl The docker container is here:

* https://github.com/SciRuby/sciruby-notebooks
* https://registry.hub.docker.com/u/minad/sciruby-notebooks/

**Comment by bollwyvl** [comment]
Thanks for the update!

As to when that update hits... well, there is still some pushback on "too
much pretty," as well as some infrastructure issues. But soon, I hope!

**Pull request merged**
