### PR TITLE
With great bower, comes great responsibility

### PR DESCRIPTION
**Pull request by rgbkrk**
* Include pygments via bower (we were using the default theme)
* Remove the bootstrap license from the base (not necessary)
* Take out Sphinx dependency (not necessary)

### CODE REVIEW

**Comment by minrk** [comment]
I didn't know pygments was a bower package.

**Comment by Carreau** [comment]
And the title of the PR was lame.

**Comment by minrk** [comment]
If by "lame" you mean "Like A Master Expert" at words.

**Comment by rgbkrk** [comment]
> And the title of the PR was lame

Alright, alright. No more [puns from Uncle Ben](http://youtu.be/fj7c3vBZ7jA?t=1m45s).

> I didn't know pygments was a bower package.

I did a [quick search](http://bower.io/search/?q=pygments) to find out if a bower package was available, which led to this [hokey pokey copy](https://github.com/xavierdutreilh/bower-pygments). Perhaps I should [submit a bower.json file](http://bower.io/docs/creating-packages/) to the [main pygments repo](https://bitbucket.org/birkenfeld/pygments-main/src).

**Pull request merged**
