### PR TITLE
Fix view as code icon

### PR DESCRIPTION
**Pull request by parente**

### CODE REVIEW

**Comment by minrk** [comment]
nbviewer shouldn't require jupyter_client anywhere. Where does that come from?

**Comment by minrk** [comment]
Nevermind, I see it's a bug in nbconvert 5.0, fixed here: https://github.com/jupyter/nbconvert/pull/499 . We can remove when nbconvert gets another release.

**Comment by parente** [comment]
Thanks for the multiple merges, @minrk.

**Comment by minrk** [comment]
Came back from the holiday with a big pile of nice PR 🎁 s. Happy 2017!

**Pull request merged**
