### PR TITLE
prepare to put it on pypi

### LINKED ISSUE #704: release jupyter/nbviewer as a pypi package
It'd be so awesome if we can just `pip install -U nbviewer` and then `python -m nbviewer`.

### PR DESCRIPTION
**Pull request by minrk**
call it 1.0 and update a couple of links in setup.py

closes #704

### CODE REVIEW

**Comment by parente** [comment]
Does the setup.py trigger the invoke logic which bundling of the jupyter notebook frontend assets that also have to wind up in the package?

**Comment by minrk** [comment]
@parente I just noticed that it doesn't, so you'd have to be careful to run it before upload. I'll add that before finishing this PR.

**Comment by parente** [comment]
LGTM. If you're done, I can give it a whirl here if you want before merging.

**Comment by parente** [comment]
I've been remiss in testing it locally. Let's merge and address problems in follow-on PRs.

**Pull request merged**
