### PR TITLE
Fix Gist support with GHE

### LINKED ISSUE #865: Gist support does not work with GHE
**Describe the bug**
When configured to integrate with GitHub Enterprise, Gists do not work.

**To Reproduce**
Enter Gist URL, e.g. https://ghe.mycompany.com/gist/c3ca62e42d590f81c3a906824b2528b0, in an nbviewer configured `GITHUB_API_URL=https://ghe.mycompany.com/v3/api/`.

**Expected behavior**
The notebook in the Gist is rendered in nbviewer.

**Additional context**
Related to #850 and #863.

### PR DESCRIPTION
**Pull request by ivan-gomes**
Closes #865.
> **Describe the bug**
> When configured to integrate with GitHub Enterprise, Gists do not work.
> 
> **To Reproduce**
> Enter Gist URL, e.g. https://ghe.mycompany.com/gist/c3ca62e42d590f81c3a906824b2528b0, in an nbviewer configured `GITHUB_API_URL=https://ghe.mycompany.com/v3/api/`.
> 
> **Expected behavior**
> The notebook in the Gist is rendered in nbviewer.
> 
> **Additional context**
> Related to #850 and #863.

### CODE REVIEW

**Comment by krinsman** [comment]
Ditto the comments on https://github.com/jupyter/nbviewer/pull/864

**Comment by ivan-gomes** [comment]
> Can you post some screenshots of the testing for this which you've done locally?

Unfortunately I can't do that. If there is another way to demonstrate it that you can recommend, I would be happy to try.

> Were there still any issues after you ran this modified version of NBViewer?

Other GHE related issues are https://github.com/jupyter/nbviewer/issues/863 and https://github.com/jupyter/nbviewer/issues/865. These three are all GHE related issues that we identified, which I believe cover all the features.

**Comment by krinsman** [comment]
The questions about this I have are similar to the ones for #864 but

Why do the strings have to be raw strings?

What is the purpose of the `GIST_URL` environment variable? 

I agree that the way this is written it doesn't seem to cause any harm, since the default behavior is the same as the previous behavior in master. 

Would the value of `GIST_URL` be any different from the value of `GITHUB_API_URL` for a GitHub Enterprise user? 

What is the expected relationship between the values of `GITHUB_API_URL` and `GIST_URL`?

Would it make sense to change the name of the environment variable to be `GIST_GITHUB_API_URL` or something like that?  

Would it also be possible to add one or two lines to the README (unfortunately NBViewer doesn't have a standalone `docs` folder yet) explaining what the environment variable does and what its value should be set to for anyone who wants to use it? (And would it be used only by people using GitHub Enterprise?)

What is the section under the comment `#embedded in URL` doing?

Also I wonder if `GIST_URL` and `GITHUB_API_URL` are typically expected to have the same value, if it would make more sense to have that be a setting for the NBViewer application which is then passed to the `BaseHandler` and then could be accessed that way?

**Comment by ivan-gomes** [comment]
> Why do the strings have to be raw strings?

The motivation was to directly parallel the `url_rewrites` for the non-GHE cases right above: https://github.com/jupyter/nbviewer/blob/0ddbaf1fcc915b6bb84dff56b8406bb66c65d387/nbviewer/providers/gist/handlers.py#L315-L316

> What is the purpose of the `GIST_URL` environment variable?

The `GIST_URL` is the base path for Gists, which in the public context is https://gist.github.com/ (default) but for GHE is different, e.g. https://ghe.mycompany.com/gist. I do not know whether the path is configurable, so I thought it would be safest to make it an environment variable instead of assuming `gist/` derived from `GITHUB_API_URL`. I am fine with `GITHUB_API_URL - 'api/v3/' + 'gist/'` if preferred.

> I agree that the way this is written it doesn't seem to cause any harm, since the default behavior is the same as the previous behavior in master.
> 
> Would the value of `GIST_URL` be any different from the value of `GITHUB_API_URL` for a GitHub Enterprise user?

Addressed above. Examples: `GIST_URL=https://ghe.mycompany.com/gist/` and `GITHUB_API_URL=https://ghe.mycompany.com/api/v3/`.

> What is the expected relationship between the values of `GITHUB_API_URL` and `GIST_URL`?

Addressed above. In my sample size of one, `GIST_URL` = `GITHUB_API_URL` - 'api/v3/' + 'gist/'.

> Would it make sense to change the name of the environment variable to be `GIST_GITHUB_API_URL` or something like that?

It's not quite an API url, more a base path/url. I think `GIST_BASE_URL` is a better alternative.

> Would it also be possible to add one or two lines to the README (unfortunately NBViewer doesn't have a standalone `docs` folder yet) explaining what the environment variable does and what its value should be set to for anyone who wants to use it? (And would it be used only by people using GitHub Enterprise?)

Yes, I will add to the README soon. And yes, the only use case I see is with GHE.

> What is the section under the comment `#embedded in URL` doing?

It is redirecting a user input of `https://ghe.mycompany.com/gist/XYZ` to `<nbviewer_base_path/gist/XYZ`. Directly parallels https://github.com/jupyter/nbviewer/blob/0ddbaf1fcc915b6bb84dff56b8406bb66c65d387/nbviewer/providers/gist/handlers.py#L315-L316.

> Also I wonder if `GIST_URL` and `GITHUB_API_URL` are typically expected to have the same value, if it would make more sense to have that be a setting for the NBViewer application which is then passed to the `BaseHandler` and then could be accessed that way?

Addressed above.

**Comment by krinsman** [comment]
OK this looks good to me, just like the other PR's. 

Would it be possible to change the name of the `gist_url` variable to `gist_base_url` or something like that? `GistClientMixin` doesn't have an attribute named `gist_url` yet, but I am worried about people looking at this several years from now without context finding `gist_url` to be too broad or assuming it does other things which it does not do.

I agree with your suggestion to change the value of the `gist_base_url`/`gist_url` to `GITHUB_API_URL` - `api/v3/` + `gist/`. As you pointed out, there is the extra price of adding extra assumptions to the code which might become invalid over time, but (1) it would decrease the amount of manual configuration the end-user needs to perform, and (2) I could imagine some users being confused about exactly they need to set the value of the environment variable to be. Making it as easy as possible for users seems like it should be a priority inasmuch as the features of NBViewer are not yet thoroughly documented.

**Comment by ivan-gomes** [comment]
Will try to address those and tag you when it could use your eyeballs.

**Comment by ivan-gomes** [comment]
@krinsman how's that look?

**Comment by krinsman** [comment]
This looks really good to me! Easy to read and understand.

Regarding the checks for whether GitHub Enterprise is being used, would it be possible to use the same
```  if os.environ.get('GITHUB_API_URL', '') != '':```
check you have in line 327 throughout?

I know I'm overthinking this, but because of the stuff with the slashes and computers being overly literal (i.e. stupid), I'm afraid that the earlier checks of the form:
``` if self.github_url == 'https://github.com/':```
could lead to unintended behavior?

On the other hand, the earlier checks do have the benefit of making full use of the `github_url` property of `GitHubClientMixin`/`GistClientMixin`. 

I don't know if there's something in urllib which would cover all possible variants of `http://github.com`, `https://github.com`, `http://github.com/`, `https://github.com/`, etc., but maybe that could be an alternative to re-computing the value of `self.github_url` directly via the environment variable?

You're right, `https://github.com` is effectively the default value for `github_url`
https://github.com/jupyter/nbviewer/blob/master/nbviewer/providers/github/handlers.py#L67
so I guess it shouldn't lead to unexpected behavior.

It still seems kind of brittle though, since really what we want to do in all cases is check whether the value of `GitHubClientMixin`'s `github_url` property is equal to its default or not (regardless of what that default value is, which maybe could be changed in future PR's and then unintentionally break things), and if not assume that GitHub Enterprise is being used. But there doesn't seem to be a clean interface for doing that.

Maybe some sort of observer pattern using traitlets and `observe`/`validate`? 
https://traitlets.readthedocs.io/en/stable/using_traitlets.html

Honestly I'm really not sure at all either way, and am looking/asking for your opinion on all of this as much as I'm doing anything else. Sorry again for the ridiculous nitpicks.

**Comment by krinsman** [comment]
At the very least maybe adding comments to the code making explicit that

> what we want to do in all cases is check whether the value of GitHubClientMixin's github_url property is equal to its default or not (regardless of what that default value is, which maybe could be changed in future PR's and then unintentionally break things), and if not assume that GitHub Enterprise is being used

so that if something gets broken in a future PR because someone changes the default value of `github_url`, it will take them less time to figure out what happened.

**Comment by ivan-gomes** [comment]
> the earlier checks do have the benefit of making full use of the `github_url` property of `GitHubClientMixin`/`GistClientMixin`.

That was exactly the intent. The Mixin isn't available for `url_rewrite` which is why it's not used there.

However, I agree with your points and think a clean solution could be to introduce a `gist_base_url` def to `GistClientMixIn` that mirrors https://github.com/jupyter/nbviewer/blob/8a8fd298b446096dddc874da57e99dd22a2d8d97/nbviewer/providers/github/handlers.py#L62-L72 and is re-used in both places. That way there is only one place to maintain the default `github_url` matching condition and default `gist_base_url` value. It won't address the `url_rewrite` case, but there's not much to be done there without a heavier refactor.

**Comment by krinsman** [comment]
OK, well maybe a comment above line 101 pointing out that `https://github.com/` is supposed to be the default value of `self.github_url`, and the point is that if it isn't equal to the default the assumption is because Github Enterprise is available would still be helpful.

Regardless the substance is already good as is, so I will request @parente review before merging. Again I think the comment clarifying that would still be helpful though, in case a slash gets added or removed to the default value sometime in the future and everything breaks and no one knows why.

**Pull request merged**
