### PR TITLE
Fix issue #848: A Conda related error is thrown during a Docker build of nbviewer.

### LINKED ISSUE #848: A Conda related error is thrown during a Docker build of nbviewer.
**Describe the bug**
A Conda related error is thrown during a Docker build of nbviwer.

**To Reproduce**

1. `git clone git@github.com:jupyter/nbviewer.git`
1. `cd nbviewer`
1. `docker build -t nbviewer .`

```
Step 13/34 : RUN conda install --file requirements.txt
 ---> Running in a4960416b2f4
Solving environment: ...working... failed

CondaUpgradeError: This environment has previously been operated on by a conda version that's newer
than the conda currently being used. A newer version of conda is required.
  target environment location: /opt/conda
  current conda version: 4.5.12
  minimum conda version: 4.7


The command '/bin/sh -c conda install --file requirements.txt' returned a non-zero code: 1
```

**Expected behavior**

No errors.

**Additional context**

* Docker version 18.09.6, build 481bc77
* OS info:
    - Distributor ID:	Ubuntu
    - Description:	Ubuntu 18.04.3 LTS
    - Release:	18.04
    - Codename:	bionic

### PR DESCRIPTION
**Pull request by dm-wyncode**
modified:   Dockerfile
fix #848

### CODE REVIEW

**Comment by dm-wyncode** [comment]
screenshot616
No errors on Docker build after changing the Miniconda version.

**Comment by krinsman** [comment]
To make the PR pass, try making the changes seen here: 
https://github.com/jupyter/nbviewer/pull/843/commits/a3fd5e3e1d9a65cc1e61509625d98d87f0b479e0
at least they worked for me

**Comment by parente** [comment]
Thanks for the PR @dm-wyncode and the help getting it to pass @krinsman.

Either this PR or #843 will need to merge first and the other rebased on master after it. I'm leaning toward merging this one first, but that means another rebase for you @krinsman in your series of PRs. Are you OK with that?

**Comment by krinsman** [comment]
Yeah, let's merge this one first!

**Pull request merged**
