### PR TITLE
adding format /slides/ for reveal.js

### PR DESCRIPTION
**Pull request by bollwyvl**
Reveal.js `master` just went [3.0](https://github.com/hakimel/reveal.js/releases/tag/3.0.0): congratulations, @hakimel, and thanks for all your hard work! :trophy:

This, and the fact that bower has quieted down (#378 and #388), made it an auspicious time to reintroduce the reveal.js-based /slides/ format originally thieved from #150, and to finish off the review debt of #359 incurred by my cowboy coding. While I couldn't help myself, and did move formats out of `app`, this should be a much more manageable chunk of changes to review.

From a UI point of view, it looks exactly the same. I certainly welcome feedback on any choices made there!

Under the hood, differences from the last slides PR:
- moved formats into their own file, as it was starting to get unwieldy
  - these still need to probably refactored (in another PR...) into either:
    - singleton classes
    - a deep config object
- passing the whole format to render (API change!) so that the reveal-specific post-processing can be done by the format

Thanks for all the support in getting (back) here!

### CODE REVIEW

**Comment by rgbkrk** [comment]
Slick! Thanks for resubmitting this.

**Comment by bollwyvl** [comment]
Yeah, it had been gnawing on my brain after working those other things,
just didn't find time to do it. It was clutch to have the reveal bump to
bring in a bunch of the fixes that have been stewing on their dev branch:
the pdf stylesheet very nearly works, but again, would rather fix that
separately!

**Comment by rgbkrk** [comment]
This likely conflicts with changes from #392, which I just merged.

**Comment by bollwyvl** [comment]
Rebased! However, I'll take a look to see if I can make any additional use of LESS to make the slides better...

**Comment by bollwyvl** [comment]
Yeah, the run-time theme thing makes combining all of the CSS hard:
- reveal.css +
- _theme_.css +
  - (can be changed with ? param) 
- zenburn.css +
  - more highlightjs syntax highlighting (really?)
    - need to investigate if this is even needed
- notebook.css +
- slides.css

still looking into it, not getting it out tonight, i guess :)

**Comment by damianavila** [comment]
zenburn is no needed and I will get rid of it on master today... so feel free to remove it here too...

**Comment by bollwyvl** [comment]
Yeah, kinda gave up on combining anything much of the reveal stuff; between the theme and the printing stuff, everything's gotta be just so, and changeable at runtime. Good to drop yet another formatter library, though!

**Comment by damianavila** [comment]
>Yeah, kinda gave up on combining anything much of the reveal stuff; between the theme and the printing stuff, everything's gotta be just so, and changeable at runtime.

Yes... reveal itself is enough complex, so combining things can be pretty hard... I am fine with change things at runtime... I will review this PR today, thanks again for working on this... I love to see the slides finally in nbviewer...

**Comment by bollwyvl** [comment]
@damianavila so true re: reveal. Thanks in advance for the review... and of course all your work in getting it started!

I do look forward to when we can circle back around and pump up the metadata and other goodies in slideshow toolbar, nbconvert... and honestly, I'd love to see live_reveal grow into something far more powerful. In the meantime, going to try to pitch in some on 3.0 issues :)

**Comment by damianavila** [comment]
code LGTM... trying to test locally right now...

**Comment by damianavila** [comment]
>I'd love to see live_reveal grow into something far more powerful

I agree :wink:
I would love to hear your ideas... maybe in an issue in the live_reveal repo to avoid hijacking this PR...

**Comment by rgbkrk** [comment]
I promise after you rebase this we can work at merging it.

@damianavila how did your testing go?

**Comment by bollwyvl** [comment]
Ok! Looking forward to it!

**Comment by bollwyvl** [comment]
Rebased. Still not quite happy with the header transition (breadcrumbs) or
the mathjax re-calling (because reveal), but otherwise pretty good to go.
The new default reveal theme looks pretty good with the more spare BS3.

**Comment by bollwyvl** [comment]
Muahaha!

**Comment by damianavila** [comment]
I guess this is already deployed but I can not see it... do you have any example working? Thanks!

**Comment by bollwyvl** [comment]
Does not appear to have been deployed yet. Current master is broken, so we
have to get that squared away first. Should be soon, though!

**Comment by damianavila** [comment]
OK, running from HEAD~1 I can see the slideshow... great work!!
There are things to work on later, regarding styling and some other issues (overflow, etc)... but this is really great! thanks for pushing it forward!!
BTW, 15 days later and now is really easy to setup the dev environment... ie, package.json helped a lot, still I have a lot of catch up after the vacatons :wink:

**Comment by bollwyvl** [comment]
Looks like this is deployed!
Here's a nice one about [DEAP, an evolutionary programming library](http://nbviewer.ipython.org/format/slides/github/lmarti/evolutionary-computation-course/blob/master/AEC.06%20-%20Evolutionary%20Multi-Objective%20Optimization.ipynb#/).

**Comment by damianavila** [comment]
:+1:

**Pull request merged**
