### PR TITLE
Add support for a 'script' format

### PR DESCRIPTION
**Pull request by yuvipanda**
- Runs the ipynb file through the ScriptExporter
- Sets Content-Type to text/plain
- Allows formatters that need to specify Content-Type

### CODE REVIEW

**Comment by yuvipanda** [comment]
Avenue for (later?) improvement - add support for 'raw' formats that don't go through the jinja templating system.

**Comment by minrk** [comment]
What would be the point of a 'raw' format, since all nbviewer does is render existing notebooks already publicly available? If there's no change to make, isn't that just downloading directly from the original URL?

**Comment by yuvipanda** [comment]
Oh, 'raw' as in 'does not go through jinja2' - right now I unnecessarily
pass the output straight through Jinja for no reason. Same for a PDF
format...

**Comment by yuvipanda** [comment]
Thanks for merging!

**Comment by yuvipanda** [comment]
@minrk and a 'raw' as you mentioned would still be useful for local providers.

**Comment by minrk** [comment]
Ah, raw as in doesn't go through jinja makes sense (though PDF *does* go through jinja to latex, and then to PDF).

**Comment by yuvipanda** [comment]
Yup, just no second layer of Jinja :)

**Pull request merged**
