### PR TITLE
Remove Mathjax render on fragments-related events.

### PR DESCRIPTION
**Pull request by damianavila**
This is related with https://github.com/jupyter/nbconvert/pull/81

### CODE REVIEW

**Comment by damianavila** [comment]
I don't think the failure is related... but... maybe I am missing something?

**Comment by bollwyvl** [comment]
Hm, can't recall why that would have been in there... what pain is it causing you? Can you link to a notebook that demonstrates why this is a good thing?

**Comment by damianavila** [comment]
Check this comment: https://github.com/jupyter/nbconvert/issues/79#issue-98542872

**Comment by bollwyvl** [comment]
Ah, thanks for the context.

I do worry about them resizing themselves, as mathjax does some dirty tricks. But if it's causing someone issues, let's go ahead and see if it bothers _someone else_!

**Pull request merged**
