### PR TITLE
Support --base-url

### PR DESCRIPTION
**Pull request by parente**
Make nbviewer relocatable behind a proxy (e.g., as a Jupyter Hub service)

### CODE REVIEW

**Comment by parente** [comment]
The approach of prefixing all URLs created across all providers and core pages is getting too invasive. I'm going to back up and try a `from_base` function for use in templates that only affects absolute paths and nothing else.

**Comment by parente** [comment]
New approach is cleaner, but the slide down of the header is not working. Need to look.

**Comment by parente** [comment]
@minrk We spoke about this work briefly in gitter last week. It's prereq to #639 which will make it possible to protect nbviewer with Jupyter Hub service auth.

I think this PR can be reviewed independently of the auth implementation. It's useful for relocating nbviewer in certain situations regardless.

**Comment by minrk** [comment]
Great, thanks @parente!

**Pull request merged**
