### PR TITLE
Fix repo and user links for GHE

### LINKED ISSUE #863: Repo and user links do not work with GHE
**Describe the bug**
When configured to integrate with GitHub Enterprise, links to repositories and users/orgs do not work.

Examples:
* https://ghe.mycompany.com/ivangomes
* https://ghe.mycompany.com/ivangomes/myproject 

**To Reproduce**
Enter GHE URL like https://ghe.mycompany.com/ivangomes in an nbviewer deployment configured with GHE.

**Expected behavior**
Get redirected to https://nbviewer.mycompany.com/github/ivangomes and see the navigation UI, like in https://nbviewer.jupyter.org/github/jupyter/nbviewer/tree/master/

**Additional context**
Related to #850.

### PR DESCRIPTION
**Pull request by ivan-gomes**
Closes #863.

> **Describe the bug**
> When configured to integrate with GitHub Enterprise, links to repositories and users/orgs do not work.
> 
> Examples:
> 
>     * https://ghe.mycompany.com/ivangomes
> 
>     * https://ghe.mycompany.com/ivangomes/myproject
> 
> 
> **To Reproduce**
> Enter GHE URL like https://ghe.mycompany.com/ivangomes in an nbviewer deployment configured with GHE.
> 
> **Expected behavior**
> Get redirected to https://nbviewer.mycompany.com/github/ivangomes and see the navigation UI, like in https://nbviewer.jupyter.org/github/jupyter/nbviewer/tree/master/
> 
> **Additional context**
> Related to #850.

### CODE REVIEW

**Comment by krinsman** [comment]
Can you post some screenshots of the testing for this which you've done locally?

Were there still any issues after you ran this modified version of NBViewer?

**Comment by ivan-gomes** [comment]
> Can you post some screenshots of the testing for this which you've done locally?
Unfortunately I can't do that. If there is another way to demonstrate it that you can recommend, I would be happy to try.

> Were there still any issues after you ran this modified version of NBViewer?
Other GHE related issues are https://github.com/jupyter/nbviewer/issues/867 and https://github.com/jupyter/nbviewer/issues/865. These three are all GHE related issues that we identified, which I believe cover all the features.

**Comment by krinsman** [comment]
Sorry about that. Admittedly I know very little about GitHub Enterprise, since I've never used it personally. Is it not possible to make a dummy repo and post pictures of that?

Would it be possible to explain the answers to some of these questions and/or add the answers as comments to the PR?

What is the motivation for changing the variable name from `github_api_url` to `github_url`?

Why do the strings need to be changed to raw strings? 

Why do the forward slashes need to be removed?

How do the changes to the rewrites account for URLs starting with `ghe.` corresponding to GitHub Enterprise? 

When you say "enter the URL", do you mean the search box on the default front page? E.g. like
Captura de Pantalla 2019-11-20 a la(s) 11 26 56 a  m

**Comment by ivan-gomes** [comment]
> What is the motivation for changing the variable name from `github_api_url` to `github_url`?

Right now `github_api_url` is being substringed twice - https://github.com/jupyter/nbviewer/blob/8a8fd298b446096dddc874da57e99dd22a2d8d97/nbviewer/providers/github/handlers.py#L440-L445. The idea was to instead define a variable that does it once and re-uses it instead of introducing two more instances of the same substring.

> Why do the strings need to be changed to raw strings?

The motivation was to directly parallel the `url_rewrites` for the non-GHE cases right above: https://github.com/jupyter/nbviewer/blob/de113fb9330925fa945f61bd3edd0ec0892b5eda/nbviewer/providers/github/handlers.py#L371-L387

> Why do the forward slashes need to be removed?

The idea is to support both `https://ghe.mycompany.com/ivangomes/myproject` and `https://ghe.mycompany.com/ivangomes/myproject/` in the same way that both cases are handled for github.com. However, for github.com it is fixed by https://github.com/jupyter/nbviewer/blob/de113fb9330925fa945f61bd3edd0ec0892b5eda/nbviewer/providers/github/handlers.py#L356 and https://github.com/jupyter/nbviewer/blob/de113fb9330925fa945f61bd3edd0ec0892b5eda/nbviewer/providers/github/handlers.py#L356. Given the comment https://github.com/jupyter/nbviewer/blob/de113fb9330925fa945f61bd3edd0ec0892b5eda/nbviewer/providers/github/handlers.py#L347-L351, I figured the preferred way was to handle it in `url_rewrites`. An alternative would be to instead introduce three `default_handlers` that mirror https://github.com/jupyter/nbviewer/blob/de113fb9330925fa945f61bd3edd0ec0892b5eda/nbviewer/providers/github/handlers.py#L352-L354 for GHE.

> How do the changes to the rewrites account for URLs starting with `ghe.` corresponding to GitHub Enterprise? Is that what the `github_api_url` variable accounts for?

Not sure I understand the question. Specifying the `GITHUB_API_URL` environment variable activates this code path and adds `url_rewrites` that convert a user input like `https://ghe.mycompany.com/ivangomes/myproject/` to `<nbviewer_base_path/github/ivangomes/myproject`.

> When you say "enter the URL", do you mean the search box on the default front page? E.g. like
> Captura de Pantalla 2019-11-20 a la(s) 11 26 56 a m

Yes that is what I mean.

> Looking at this more and more it looks like it's correct/the right changes, I just want to make sure I understand the changes.
> 
> Would it be possible to add a comment explaining that basically the rewrites you added are the same as the default GitHub rewrites, except that they begin with the value of the `GITHUB_API_URL` environment variable instead of `https://github.com`? (Also, is that a correct interpretation of what's going on?)

I think the confusion might stem from the fact that if I enter a full URL like to a GitHub repo, e.g. https://github.com/jupyter/nbviewer/ in https://nbviewer.jupyter.org/ it miraculously redirects to https://nbviewer.jupyter.org/github/jupyter/nbviewer/tree/master/ even though it doesn't match https://github.com/jupyter/nbviewer/blob/8a8fd298b446096dddc874da57e99dd22a2d8d97/nbviewer/providers/github/handlers.py#L428-L429.

If I'm remembering my trace properly this is because of a sequence of non-obvious redirects:
1) `/urls/github.com%2Fjupyter%2Fnbviewer%2F caused by https://github.com/jupyter/nbviewer/blob/8a8fd298b446096dddc874da57e99dd22a2d8d97/nbviewer/providers/url/handlers.py#L112
2) `github/jupyter/nbviewer` caused by https://github.com/jupyter/nbviewer/blob/8a8fd298b446096dddc874da57e99dd22a2d8d97/nbviewer/providers/github/handlers.py#L397
3) `github/jupyter/nbviewer/master/tree` caused by https://github.com/jupyter/nbviewer/blob/8a8fd298b446096dddc874da57e99dd22a2d8d97/nbviewer/providers/github/handlers.py#L428-L429

Again, given the comment at https://github.com/jupyter/nbviewer/blob/8a8fd298b446096dddc874da57e99dd22a2d8d97/nbviewer/providers/github/handlers.py#L392-L396 I figured this wasn't desired so I instead went with this implementation.

Hope that clarifies things!

**Comment by krinsman** [comment]
Your understanding of the redirect system seems correct to me; thank you so much for putting so much thought and effort into this! I agree with you, this looks like the correct approach amongst the available alternatives.

To clarify, the value of `GITHUB_API_URL` is `ghe.mycompany.com`?

Would it be possible to change the name of the `github_url` variable to `github_api_base_url` or something else like that?

The `GitHubClientMixin` already has an attribute (actually a property) with the name `github_url`, so calling it `github_url` might be confusing.

https://github.com/jupyter/nbviewer/blob/5ed1e019bfc7bef409f1c1f5b7aaca955a1b6400/nbviewer/providers/github/handlers.py#L62

Other than that I would recommend that this be merged -- I only have triage but not write access myself.

**Comment by ivan-gomes** [comment]
Will look into that and tag you for review.

**Comment by ivan-gomes** [comment]
@krinsman ready for ya. :)

**Comment by krinsman** [comment]
@ivan-gomes Sorry for the delay -- this looks good to me!

I'll request that the maintainer of this repository take a look at it. He's very busy though, so please keep in mind that it may take a while.

**Comment by parente** [comment]
Thanks @ivan-gomes for submitting this and your other GHE PRs, and @krinsman for reviewing them. 💯 🥇  

I'm taking a quick look at them now and running them locally to see if there are any surprise changes to the public GitHub handling behavior. I don't have a GHE account to test an alternative GitHub URL, but that's in no way a blocker to shipping these improvements. We can iterate if tweaks are required in the wild.

**Comment by ivan-gomes** [comment]
Thanks @parente and @krinsman. Please feel free to tag me in GHE related issues/PRs. Would be happy to look into patching and testing.

**Pull request merged**
