### PR TITLE
use jupyter branding

### PR DESCRIPTION
**Pull request by bollwyvl**
Once the new jupyter site hits with the new design, we should be ready to follow suit, suitably modified to meet the different use case. Overall, let's use this as an opportunity to make the distinction between notebook content and nbviewer "chrome" more distinct, while trying to get even more out of the way.

Open to other suggestions, of course!

Here's an initial cut.

- Home: header (jupyter header link is hovered)
screenshot from 2015-08-30 23-46-45
- home: footer
screenshot from 2015-08-30 23-49-05
- a short notebook (the footer is off the screen with a `height: 100hv` otherwise it rides up and looks funny... could be solved by actually make the body background the footer grey, and setting the "main" content to be white...)
screenshot from 2015-08-31 00-00-12

Other things:
- Probably need to update the footer to talking about _nbconvert_ and _notebook_(for assets) versions, not _ipython_.
- I do wonder about the ipython blue as the link color... but the blue is better than orange if it's everywhere.
- I am not wild about the logo treatment... positioned above the words looks better. not sure if it's even legit to use the logo this way.

### CODE REVIEW

**Comment by rgbkrk** [comment]
Awesome!

> I am not wild about the logo treatment... positioned above the words looks better. not sure if it's even legit to use the logo this way.

We could probably have @CameronOelsen and @ellisonbg check that out.

**Comment by bollwyvl** [comment]
Definitely would appreciate feedback... IANAD :smiling_imp: 

Here's some shamefully copy and pasted options (totally could have scripted it in a notebook):


I am sort of all about leaving it as a mixed svg/native sans-serif font, so i am interested what it looks like in not liberation sans.... what does it even resolve to on osx, win?

Got the color scheme off [palleton](http://paletton.com/#uid=70k0u0kpysCfOCJkRuXsWnLvViR), accepted all the defaults. Now that i look at it, one of the lighter-value blues might be nice.

The spacing grid is based off the size of the middle-sized moon, which is three times the size of the non-ascender/descenders (visible if opened in inkscape, though i got lazy).

I like the right-aligned, below in teal the best, but the lighter orange is good, too. The blue is really close to the default boostrap link color...

Another option would be to go to the jupyter-in-the-planetentheses, with nbviewer bigger.

**Comment by bollwyvl** [comment]
Another option would be like jupyterhub:

```
           _
       o/  \°
jupyter viewer
        •\_/
```

**Comment by bollwyvl** [comment]
Whoops!

**Comment by rgbkrk** [comment]
Since no one else jumped in with feedback and I think this is totally appropriate, maybe we can go ahead with this after you take the WIP tag off?

**Comment by bollwyvl** [comment]
@cameronoelsen Any design feedback here?

Needs a rebase, but would love some feedback. Let us know if we can help you evaluate it!

**Comment by cameronoelsen** [comment]
@bollwyvl I will draft up some variations, will have them posted by today or tomorrow!

**Comment by bollwyvl** [comment]
@cameronoelsen Awesome, thanks!

**Comment by rgbkrk** [comment]
Sweet.

**Comment by cameronoelsen** [comment]
@bollwyvl Sorry it took a day or so to get back. I have attached your screenshots and revised them:

-Made a new logo for the nbviewer site (below in svg format) using the same font as the logo, Myriad Pro.
-We need a shadow underneath the navigation bar after the user scrolls.
-If we are going to have the same kinda feel for the navigation bar, we will want to make the navbar nav items be in Helvetica Neue (will then match the site font along with the jupyter.org landing page)

nbviewer logo:
https://www.dropbox.com/s/3m3kbe8bo5ajqe1/nbviewer-logo.svg?dl=0

Besides those changes, looks great to me as well :cake: 

preview3
preview4

**Comment by bollwyvl** [comment]
> https://www.dropbox.com/s/3m3kbe8bo5ajqe1/nbviewer-logo.svg?dl=0

Please convert the new text to paths!

**Comment by cameronoelsen** [comment]
@bollwyvl Just updated, now paths!
https://www.dropbox.com/s/3m3kbe8bo5ajqe1/nbviewer-logo.svg?dl=0

**Comment by bollwyvl** [comment]
Ah, lovely. I'll get on the other things.

**Comment by ellisonbg** [comment]
Awesome, glad to see this moving forward.

On Wed, Oct 14, 2015 at 8:39 PM, Nicholas Bollweg <notifications@github.com>
wrote:

> Ah, lovely. I'll get on the other things.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jupyter/nbviewer/pull/494#issuecomment-148241969>.
>



-- 
Brian E. Granger
Associate Professor of Physics and Data Science
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by rgbkrk** [comment]
Sweet, thanks all.

**Comment by bollwyvl** [comment]
> -If we are going to have the same kinda feel for the navigation bar, we will want to make the navbar nav items be in Helvetica Neue (will then match the site font along with the jupyter.org landing page)

What you see is what you get on a basically stock Linux distro (fedora 22): no helvetica for us! However, it will at least be consistent:
screenshot from 2015-10-14 23-33-21

I am personally fine with this re: another font to load on every page.

Otherwise, I feel like it's pretty much doing the thing. Thanks for all the feedback everyone! Looking at that split screenshot, I wonder if we need a new favicon? I'll take of wip anyway, and once the tests run, this should be good to go.

Here are the test-drive shots with the current branding:

Home page
screenshot from 2015-10-14 23-26-02

...scrolled
screenshot from 2015-10-14 23-27-20

long notebook
screenshot from 2015-10-14 23-28-54

...scrolled
screenshot from 2015-10-14 23-28-58

table
screenshot from 2015-10-14 23-30-06

gist tree
screenshot from 2015-10-14 23-30-40

**Comment by cameronoelsen** [comment]
@bollwyvl That looks great!

**Comment by rgbkrk** [comment]
Re-kicked that build. Let's :shipit:

**Comment by bollwyvl** [comment]
Woo! Thanks again, everyone!

**Comment by rgbkrk** [comment]
The [build errored](https://hub.docker.com/r/jupyter/nbviewer/builds/bnyts9hgrhuukfxgeuuewml/). :frowning:

**Comment by bollwyvl** [comment]
building locally...

**Comment by bollwyvl** [comment]
looks like invoke is bad...

**Pull request merged**
