### PR TITLE
fix for Github Enterprise

### PR DESCRIPTION
**Pull request by mskimm**
github_url is corrected to the corresponding URL.

#850

### CODE REVIEW

**Comment by krinsman** [comment]
So the line
https://github.com/jupyter/nbviewer/pull/851/files#diff-f2de296d9ff85c0b7d3f77f66cbaf291R52
basically makes this "idempotent"? I.e. so that once this property is calculated, it returns the same value every subsequent time that it is called?

And would it be possible to clarify why it didn't work with GitHub enterprise previously, in spite of these lines here:
https://github.com/jupyter/nbviewer/blob/dc72153dfd9c02d1c076a6c2bb28c61b5a791ee8/nbviewer/providers/github/handlers.py#L392
because that only changes the `github_api_url`, but it's also necessary to change the `github_url` in accordance with the method described on the help page linked to in the PR?

**Comment by mskimm** [comment]
Thank you for your review.

I Intended idempotent. So I saved the result in `self._github_url` and returned it.

The code
https://github.com/jupyter/nbviewer/blob/dc72153dfd9c02d1c076a6c2bb28c61b5a791ee8/nbviewer/providers/github/handlers.py#L392

works fine. This means I can show the notebook in `http(s)://<nbviewer_url>/github/<user>/<repo>/blob/<branch_or_ref>/<path_to_ipynb>`.

The problem occurs when calling tree like`http(s)://<nbviewer_url>/github/<user>/<repo>/tree/<branch_or_ref>`.  As mentioned in #850, Calling this shows the following messages:

```
[E 190916 16:07:22 web:1670] Uncaught exception GET /github/<user>/<repo>/tree/<branch_or_ref>/ (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:5000', method='GET', uri='/github/<user>/<repo>/tree/<branch_or_ref>/‘, version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/Users/<myname>/anaconda3/envs/nbviewer/lib/python3.6/site-packages/tornado/web.py", line 1592, in _execute
        result = yield result
      File "/Users/<myname>/anaconda3/envs/nbviewer/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/Users/<myname>/anaconda3/envs/nbviewer/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
        yielded = self.gen.throw(*exc_info)
      File "/Users/<myname>/d/mskimm/nbviewer/nbviewer/providers/base.py", line 562, in cached_method
        yield method(self, *args, **kwargs)
      File "/Users/<myname>/anaconda3/envs/nbviewer/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
        value = future.result()
      File "/Users/<myname>/anaconda3/envs/nbviewer/lib/python3.6/site-packages/tornado/gen.py", line 1147, in run
        yielded = self.gen.send(value)
      File "/Users/<myname>/d/mskimm/nbviewer/nbviewer/providers/github/handlers.py", line 164, in get
        user, repo = re.match(r"^https://github\.com/(?P<user>[^\/]+)/(?P<repo>[^\/]+)/.*", example_file_url).group('user', 'repo')
    AttributeError: 'NoneType' object has no attribute 'group'
```
(Note `<user>, <repo>, <branch_or_ref> and <myname>` were replaced.)

This is why `example_file_url` starts with `https://<GITHUB_URL>`, trying to parse it as `https://github.com`.
https://github.com/jupyter/nbviewer/blob/7cf4b33afa623035ad0c321ead54501f79b54e38/nbviewer/providers/github/handlers.py#L163-L164

I tried to fix it with some extra modifications.

Feel free to let me know if it's wrong or any suggestion.

**Comment by krinsman** [comment]
This looks good to me! I don't have push rights to this repository, but hopefully this at least helps the maintainer review this more quickly when he has more time to look at this again.

**Comment by ivan-gomes** [comment]
@parente hate to bother, but we could really benefit from this being merged in.

**Comment by parente** [comment]
Thanks for your patience, everyone. I don't have a GH Enterprise account to test the changes, but I don't see any regressions. Let's :shipit: and fix as needed.

**Pull request merged**
