### PR TITLE
Update the FAQ

### PR DESCRIPTION
**Pull request by parente**
Fixes #793

### CODE REVIEW

**Comment by parente** [comment]
Happy to have someone take a look if they're interested.  I'll merge sometime this week if not.

**Comment by Carreau** [comment]
LGTM.

**Comment by parente** [comment]
Thanks @Carreau

**Comment by parente** [comment]
I've gone through the process of updating the public nbviewer once now without issue. I'll do it again with the new image from #794 and the new FAQ sometime this week hopefully.

**Comment by jzf2101** [comment]
Hey sorry about the delay this looks great

**Pull request merged**
